name: ShorthandCommand
version: '${project.version}'
main: info.lousyboi.shorthandcommand.ShorthandCommand
api-version: 1.17
authors: [ LousyBoi ]
description: All your favourite commands but short
commands:
  gmc:
    description: Changes gamemode to creative
    usage: /gmc
    permission: shorthandCommands.gmc
  gma:
    description: Changes gamemode to adventure
    usage: /gma
    permission: shorthandCommands.gma
  gms:
    description: Changes gamemode to survival
    usage: /gms
    permission: shorthandCommands.gms
  gmsp:
    description: Changes gamemode to spectator
    usage: /gmsp
    permission: shorthandCommands.gmsp
  day:
    description: Changes time to day
    usage: /day
    permission: shorthandCommands.timeChange
  night:
    description: Changes time to night
    usage: /night
    permission: shorthandCommands.timeChange
  peaceful:
    description: Change difficulty to peaceful
    usage: /peaceful
    permission: shorthandCommands.difficulty
  easy:
    description: Change difficulty to easy
    usage: /easy
    permission: shorthandCommands.difficulty
  normal:
    description: Change difficulty to normal
    usage: /normal
    permission: shorthandCommands.difficulty
  hard:
    description: Change difficulty to hard
    usage: /hard
    permission: shorthandCommands.difficulty